courses/urls.py
from django.urls import path, include
from . import views

app_name = 'courses'

urlpatterns = [
	path('', views.CourseList.as_view(), name='list'),
	path('mycourses/', views.MyCourseList.as_view(), name='my_courses'),
	path('create/', views.course_create, name='create'),

	path('<str:course_slug>/', include([
			path('', views.course_detail, name='detail'),
			path('update/', views.course_update, name='update'),
			path('delete/', views.course_delete, name='delete'),
			path('chapters/', views.chapter_list, name='chapter_list'),
			path('chapters/create/', views.chapter_create, name='chapter_create'),
			path('chapters/<str:chapter_slug>/',include(([
					path('', views.chapter_detail, name='detail'),
					path('update/', views.chapter_update_info, name='update_info'),
					path('update/content/', views.chapter_update_content, name='update_content'),
					path('delete/', views.chapter_delete, name='delete'),
				], app_name), namespace='chapter')
	),
		])
	),


]

users/urls.py
from django.urls import path
from users import views as users_views


urlpatterns = [
	path('teacher/<int:pk>/', users_views.teacher_profile, name='teacher_profile'),
	path('student/<int:pk>/', users_views.student_profile, name='student_profile'),

	path('profile/', users_views.profile, name='profile'),
	path('login/', users_views.login, name='login'),
	path('logout/', users_views.logout, name='logout'),
	path('signup/', users_views.signup, name='signup'),
	path('signup/student/', users_views.student_signup, name='student_signup'),
	path('signup/teacher/', users_views.teacher_signup, name='teacher_signup'),
	path('change_password/', users_views.change_password, name='change_password'),
	path('reset/done/', users_views.password_reset_complete, name='password_reset_done'),
]

courses/models.py
from django.db import models
from django.urls import reverse
from users.models import Teacher, Student
from ckeditor_uploader.fields import RichTextUploadingField


class Course(models.Model):
	slug 		= models.SlugField(unique=True)
	name 		= models.CharField(max_length=50)
	detail 		= models.CharField(max_length=250, verbose_name='About the course')
	thumbnail 	= models.ImageField(upload_to='courses/thumbnails/', null=True)

	teacher 	= models.ForeignKey(Teacher, on_delete=models.CASCADE)
	students 	= models.ManyToManyField(Student, related_name='students_to_course')

	created_date 		= models.DateTimeField(auto_now_add=True)
	last_update_date 	= models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("courses:detail", kwargs={"course_slug": self.course.slug})

	def get_thumbnail_url(self):
		if self.thumbnail:
			return self.thumbnail.url
		else:
			return '/media/courses/thumbnails/default.jpg'

	def get_slug(self):
		def get_updated_qs(slug):
			return Course.objects.filter(slug=slug.lower()).order_by("-id")
		return create_slug(get_updated_qs(self.name), get_updated_qs, self.name)


class Chapter(models.Model):
	slug 		= models.SlugField()
	name 		= models.CharField(max_length=20)
	detail 		= models.CharField(max_length=250, verbose_name='About the chapter')
	index 		= models.IntegerField(default=1, null=False)
	content 	= RichTextUploadingField(null=True)

	course 		= models.ForeignKey(Course, on_delete=models.CASCADE)

	created_date		= models.DateTimeField(auto_now_add=True)
	last_update_date 	= models.DateTimeField(auto_now=True)


	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("courses:chapter:detail", kwargs={
				"course_slug": self.course.slug,
				"chapter_slug": self.slug
		    })

	def get_slug(self):
		def get_updated_qs(slug):
			return self.course.chapter_set.filter(slug=slug.lower()).order_by("-id")

		return create_slug(get_updated_qs(self.name), get_updated_qs, self.name)

	def get_next_index(self):
		if self.course.chapter_set:
			return len(self.course.chapter_set.all()) + 1
		else:
			return 1


def create_slug(qs, get_updated_qs, name):
	name = name.replace(' ', '-').lower()
	slug = name
	count = 0

	while qs.exists():
		slug = f'{name}-{qs.count() + count}'

		count += 1
		qs = get_updated_qs(slug)

	return slug

courses/forms.py
from django import forms
from .models import Course, Chapter


class CourseCreateForm(forms.ModelForm):
	thumbnail = forms.ImageField(required=False)

	class Meta:
		model = Course
		fields = ('name', 'detail', 'thumbnail')


class CourseEditForm(forms.ModelForm):
	thumbnail = forms.ImageField(required=False)

	class Meta:
		model = Course
		fields = ('name', 'detail', 'thumbnail')


class ChapterCreateInfoForm(forms.ModelForm):

	class Meta:
		model = Chapter
		fields = ('name', 'detail', )


class ChapterEditInfoForm(forms.ModelForm):

	class Meta:
		model = Chapter
		fields = ('name', 'detail', )


class ChapterEditContentForm(forms.ModelForm):

	class Meta:
		model = Chapter
		fields = ('content',)
		labels = {'content': ''}

courses/views.py
from django.shortcuts import (
		render,
		redirect,
		get_object_or_404
	)
from .forms import (
		CourseCreateForm,
		CourseEditForm,
		ChapterCreateInfoForm,
		ChapterEditInfoForm,
		ChapterEditContentForm,
	)
from .decorators import (
		teacher_required,
		teacher_owner_required,
	)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.contrib import messages
from django.urls import reverse
from users.models import Teacher
from .models import Course, Chapter


@teacher_required
def course_create(request):
	if request.method == 'POST':
		form = CourseCreateForm(request.POST, request.FILES)

		if form.is_valid():
			course = form.save(commit=False)
			teacher = Teacher.objects.get(user=request.user)
			course.teacher = teacher
			course.save()
			messages.success(request, f'\'{course.name}\' created.')
			return redirect('courses:detail', course_slug=course.slug)
	else:
		form = CourseCreateForm()

	context = {
		'title': 'Create course',
		'form': form,
	}

	return render(request, 'courses/course_create.html', context)


class CourseList(LoginRequiredMixin, ListView):
	model = Course
	paginate_by = 20

	def get_queryset(self, *args, **kwargs):
		return Course.objects.all().order_by('-created_date')

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = 'Courses'
		context['courses_active'] = 'active'
		return context

# Mixins...
class MyCourseList(LoginRequiredMixin, ListView):
	model = Course
	paginate_by = 20

	def get_queryset(self, *args, **kwargs):
		teacher = Teacher.objects.get(user=self.request.user)
		return Course.objects.filter(teacher=teacher).order_by('-created_date')

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['title'] = 'My courses'
		context['my_courses_active'] = 'active'
		return context


def course_detail(request, course_slug):
	course = get_object_or_404(Course, slug=course_slug)
	chapter_list = course.chapter_set.all()

	context = {
		'title': course.name,
		'course': course,
		'owner': course.teacher.user_id == request.user.id,
		'chapter_list': chapter_list,
	}

	return render(request, 'courses/course_detail.html', context)


@teacher_owner_required
def course_update(request, course_slug):
	course = get_object_or_404(Course, slug=course_slug)

	if request.method == 'POST':
		form = CourseEditForm(request.POST or None,
					request.FILES or None,
					instance=course
				)

		if form.is_valid():
			form.save()
			messages.success(request, 'Course updated successfully.')
			return redirect('courses:detail', course_slug=course.slug)
	else:
		form = CourseEditForm(instance=course)

	context = {
		'title': 'Update course',
		'course': course,
		'form': form
	}

	return render(request, 'courses/course_update.html', context)


@teacher_owner_required
def course_delete(request, course_slug):
	course = get_object_or_404(Course, slug=course_slug)
	course_name = course.name
	course_slug = course.slug

	if request.method == 'POST':
		delete = request.POST.get('confirm', None)
		if delete:
			course.delete()
			messages.success(request, 'Course deleted successfully.')
			return redirect('courses:my_courses')

	context = {
		'title': 'Delete course',
		'course_name': course_name,
		'course_slug': course_slug
	}

	return render(request, 'courses/course_delete.html', context)


def chapter_list(request, course_slug):
	course = get_object_or_404(Course, slug=course_slug)
	chapter_list = course.chapter_set.all()

	context = {
		'title': course.name,
		'course': course,
		'chapter_list': chapter_list,
		'owner': course.teacher.user_id == request.user.id,
	}

	return render(request, 'chapters/chapter_list.html', context)


@teacher_owner_required
def chapter_create(request, course_slug):
	course = get_object_or_404(Course, slug=course_slug)

	if request.method == 'POST':
		form = ChapterEditInfoForm(request.POST, request.FILES)

		if form.is_valid():
			chapter = form.save(commit=False)
			chapter.course = course
			chapter.save()
			messages.success(request, f'\'{chapter.name}\' chapter created.')

			return redirect('courses:chapter:update_content',
				course_slug=course.slug,
				chapter_slug=chapter.slug,
			)
	else:
		form = ChapterEditInfoForm()

	context = {
		'title': course.name,
		'form': form,
	}

	return render(request, 'chapters/chapter_create.html', context)


def chapter_detail(request, course_slug, chapter_slug):
	course = get_object_or_404(Course, slug=course_slug)
	# Getting the chapter from course__chapter_set, so no need for @decorators
	chapter = get_object_or_404(course.chapter_set, slug=chapter_slug)
	chapter_set = course.chapter_set

	context = {
		'title': course.name,
		'course': course,
		'chapter': chapter,
		'owner': course.teacher.user_id == request.user.id,
	}
	if chapter.index > 1:
		context['previous'] = chapter_set.get(index=chapter.index - 1).get_absolute_url()

	if chapter.index < chapter_set.all().count():
		context['next'] = chapter_set.get(index=chapter.index + 1).get_absolute_url()

	return render(request, 'chapters/chapter_detail.html', context)


@teacher_owner_required
def chapter_delete(request, course_slug, chapter_slug):
	course = get_object_or_404(Course, slug=course_slug)
	chapter = get_object_or_404(course.chapter_set, slug=chapter_slug)

	if request.method == 'POST':
		delete = request.POST.get('confirm', None)
		
		if delete:
			chapter.delete()
			messages.success(request, 'Chapter deleted.')

			return redirect('courses:chapter_list', course_slug=course.slug)

	context = {
		'title': 'Delete chapter',
		'course': course,
		'chapter': chapter
	}

	return render(request, 'chapters/chapter_delete.html', context)


@teacher_owner_required
def chapter_update_info(request, course_slug, chapter_slug):
	course = get_object_or_404(Course, slug=course_slug)
	chapter = get_object_or_404(course.chapter_set, slug=chapter_slug)

	if request.method == 'POST':
		form = ChapterEditInfoForm(request.POST or None,
				request.FILES,
				instance=chapter
			)
		
		if form.is_valid():
			chapter = form.save()
			messages.success(request, 'Chapter updated successfully.')
			return redirect('courses:chapter:detail',
						course_slug=course.slug,
						chapter_slug=chapter.slug,
					)

	else:
		form = ChapterEditInfoForm(instance=chapter)

	context = {
		'title': 'Update chapter',
		'course': course,
		'chapter': chapter,
		'form': form,
	}

	return render(request, 'chapters/chapter_update_info.html', context)


@teacher_owner_required
def chapter_update_content(request, course_slug, chapter_slug):
	course = get_object_or_404(Course, slug=course_slug)
	chapter = get_object_or_404(course.chapter_set, slug=chapter_slug)

	if request.method == 'POST':
		form = ChapterEditContentForm(request.POST or None, instance=chapter)
		
		if form.is_valid():
			chapter = form.save()
			messages.success(request, 'Chapter updated successfully.')
			return redirect('courses:chapter:detail',
						course_slug=course.slug,
						chapter_slug=chapter.slug,
					)

	else:
		form = ChapterEditContentForm(instance=chapter)

	context = {
		'title': 'Update chapter',
		'course': course,
		'chapter': chapter,
		'form': form,
	}

	return render(request, 'chapters/chapter_update_content.html', context)

courses/templates/courses/course_create.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
	<div class="container">
		<div class="mt-5">
			<aside class="col-12 col-md-10 col-lg-8 m-auto">
				<div class="card">
					<article class="card-body">
						<h4 class="card-title mb-4 mt-1">New course :</h4>
						<form method="POST" action="." enctype="multipart/form-data">
							{% csrf_token %}
							{{ form|crispy }}
							<input type="submit" value="submit" class="btn btn-primary">
						</form>
					</div>
				</article>
			</div>
		</aside>
	</div>
</div>
</div>
{% endblock content %}

courses/templates/courses/course_delete.html
{% extends "base.html" %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-12">
				<form method="POST" action=".">
					{% csrf_token %}
					<p>Are you sure you want to delete <span class="text-danger">{{ course_name }}</span> course?</p>
					<input type="submit" name="confirm" value="Yes, Delete" class="btn btn-danger px-3 float-right">
					<button type="button" onclick="location.href='{% url "courses:detail" course_slug %}'" class="btn btn-outline-danger px-3 mx-3 float-right">
						Cancel
					</button>
				</form>
			</div>			
		</div>
	</div>
{% endblock content %}

courses/templates/courses/course_detail.html
{% extends "base.html" %}

{% block sub_nav %}
<div class="py-2 text-center bg-dark text-white">
	<h4>
	{{ course.name }}
	{% if owner %}
		<a href="{% url 'courses:update' course.slug %}" class="text-warning">
			<i class="fas fa-edit"></i>
		</a>
	{% endif %}
	</h4>
</div>
{% endblock sub_nav %}

{% block content %}
<div class="container">
<div class="row">
	<div class="col-md-4 text-center">
		<img class="img-fluid" src="{{ course.get_thumbnail_url }}">
	</div>
	<div class="col-md-8 mt-3">
		<p>
			{{ course.detail }}
			{% if owner %}
				<a href="{% url 'courses:update' course.slug %}" class="text-primary">
					<i class="fas fa-edit"></i>
				</a>
			{% endif %}
		</p>
		<hr>
		<p>Teacher :
			<a href="{% url 'teacher_profile' course.teacher.user.id %}"
				class='{% if user.is_teacher and course.teacher.user == user %}text-danger{% endif %}'>
				<strong>
				{{ course.teacher.user.get_shortname }}
				</strong>
			</a>
		</p>
		<p>Students : {{ course.students.count }}</p>
		<p>Date : {{ course.created_date|date:'d-M-Y h:i' }}</p>
		<p>Last update : {{ course.last_update_date|date:'d-M-Y h:i' }}</p>
		{% if owner %}
			<a class="btn btn-sm float-right btn-outline-danger px-2"
				href="{% url 'courses:delete' course.slug %}">
				<i class="fas fa-times mr-2"></i>
				Delete course
			</a>
		{% endif %}
	</div>
	<div class="col-12 mt-4">
		Chapters : <a href="{% url 'courses:chapter_list' course.slug %}">see all..</a>
		{% if owner %}
			<a class="btn btn-sm float-right btn-success text-white px-2"
				href="{% url 'courses:chapter_create' course.slug %}">
				<i class="fas fa-plus-square mr-2"></i>
				Add chapter
			</a>
		{% endif %}
		{% if chapter_list %}
			<table class="table table-borderless table-striped ">
				<tbody>
					{% for chapter in chapter_list|slice:':5' %}
						{% url 'courses:chapter:detail' course.slug chapter.slug as detail_url%}
						<tr onclick="location.href='{{ detail_url }}'" style="cursor: pointer;">
							<td><i class="fas fa-book-open fa-2x ol-text-primary"></i></td>
							<td>
								<a href="{{ detail_url }}">
									{{ chapter.name }}
								</a>
							</td>
							<td class="d-none d-lg-block">{{ chapter.detail }}</td>
							<td>
								{% if owner %}
									<a class="btn btn-sm float-right btn-danger text-white px-2 ml-2"
										href="{% url 'courses:chapter:delete' course.slug chapter.slug %}">
										<i class="fas fa-trash mr-2"></i>
										Delete
									</a>
									<a class="btn btn-sm float-right btn-primary text-white px-2 "
										href="{% url 'courses:chapter:update_info' course.slug chapter.slug %}">
										<i class="fas fa-edit mr-2"></i>
										Edit
									</a>
								{% endif %}
							</td>
						</tr>
					{% endfor %}
					{% if chapter_list.count > 5 %}
						<tr onclick="location.href='{% url 'courses:chapter_list' course.slug %}'" style="cursor: pointer;">
							<td>...</td>
							<td>
								<a href="{% url 'courses:chapter_list' course.slug %}">
									Click to view the full list...
								</a>
							</td>
							<td></td>
							<td></td>
						</tr>
					{% endif %}
				</tbody>
			</table>
		{% else %}
			<p class="text-danger">No chapters, yet.</p>
		{% endif %}
	</div>
</div>
</div>
{% endblock content %}

{% block custom_style %}
<style type="text/css">
	table tr:hover {
		box-shadow: 0 0 5px -2px;
		transition: all ease 100ms;
	}
</style>
{% endblock custom_style %}

courses/templates/courses/course_item.html
<div class="p-3 col-12 col-md-6 col-lg-4">
	<div class="card ol-shadow-hover">
		<img class="card-img-top" src="{{ course.get_thumbnail_url }}" alt="" width="256" height="256">
		<div class="card-body">
			<h4 class="card-title">{{ course.name|truncatechars:18 }}</h4>
			<p class="card-text">
				{{ course.detail|truncatechars:30 }}
				<br>
				on <strong>{{ course.created_date|date:'d-m-y h:i' }}</strong>
				by <a href="{% url 'teacher_profile' course.teacher.user.id %}"
						class='{% if user.is_teacher and course.teacher.user == user %}text-danger{% endif %}'>
						<strong>
							{{ course.teacher.user.get_shortname }}
						</strong>
					</a>
				<br>
			</p>
		</div>
		<div class="text-center">
			{% if user.is_student or not user.is_authenticated %}
				{% if user.get_profile in course.students.all %}

					<span class="ol-text-primary font-weight-bold">
						25%
						<a class="ol-text-primary" href="{% url 'courses:detail' course.slug %}">Continue</a>
					</span>
					<div class="progress rounded-0" style="height:10px;">
						<div class="progress-bar rounded-0 ol-btn-bg-primary" style="width: 25%"></div>
					</div>
				{% else %}
					<a href="{% url 'courses:detail' course.slug %}" class="btn btn-block btn-primary ol-btn-bg-primary rounded-0">Enroll</a>
				{% endif %}
			{% else %}
					<a href="{% url 'courses:detail' course.slug %}" class="btn btn-block btn-secondary rounded-0">View</a>
			{% endif %}
		</div>
	</div>
</div>

courses/templates/courses/course_list.html
{% extends "base.html" %}

{% block content %}
<div class="container text-center p-2">
	{% if not course_list %}
		<h3 class="mb-4 text-primary">
				Sorry, There is no courses, yet.
		</h3>
		{% if user.is_teacher %}
			<h5 class="mb-4">Add a new course by clicking on</h5>
			<a class="btn mb-2 px-4 btn-outline-primary" href="{% url 'courses:create' %}">
				<i class="mr-1 fas fa-plus-square"></i>
				Add
			</a>
		{% endif %}
	{% else %}
		{% if user.is_authenticated %}
			<h2 class="m-4 ol-text-primary">
				Welcome back {{ user.first_name }}!
			</h2>
			{% url 'courses:my_courses' as my_courses_path %}
			{% if user.is_teacher %}
				{% if request.path != my_courses_path %}
					<h5 class="mb-4">See your courses by clicking on</h5>
					<a class="btn mb-2 px-4 btn-outline-primary btn-lg" href="{% url 'courses:my_courses' %}">
						<i class="fas fa-book-open"></i>
						My courses
					</a>
				{% else %}
					<h5 class="mb-4">Add a new course by clicking on</h5>
					<a class="btn mb-2 px-4 btn-outline-primary btn-lg" href="{% url 'courses:create' %}">
						<i class="mr-1 fas fa-plus-square"></i>
						Add
					</a>
				{% endif %}
			{% endif %}
		{% else %}
			<h2 class="m-4 ol-text-primary">Hi Stranger!</h2>
			<h5 class="mb-4">Sign up in order to take or create courses</h5>
			<a class="btn mb-2 px-4 btn-outline-primary btn-lg" href="{% url 'courses:create' %}">
				<i class="mr-1 fas fa-user-plus"></i>
				signup
			</a>
		{% endif %}
	{% endif %}
</div>		

{% if course_list %}
	<div class="container mt-3">
		<div class="row">
			{% for course in course_list %}
				{% include "./course_item.html" %}
			{% endfor %}
		</div>
	</div>
{% endif %}	

{% endblock content %}

courses/templates/courses/course_update.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block sub_nav %}
	<div class="py-2 text-center bg-dark text-white">
		<h4>{{ course.name }}</h4>
	</div>
{% endblock sub_nav %}

{% block content %}
	<div class="container">
		<form method="POST" action="." enctype="multipart/form-data">
			{% csrf_token %}
			<div class="row">
				<div class="col-4">
					<img class="img-fluid mb-2" src="{{ course.get_thumbnail_url }}">

				<!-- Manual Thumbnail field -->
					<input type="file" name="thumbnail" accept="image/*" id="id_thumbnail">
				</div>
				<div class="col-8">
					<div id="div_id_name" class="form-group">
						{{ form.name|as_crispy_field }}
					</div>
					<div id="div_id_detail" class="form-group">
						{{ form.detail|as_crispy_field }}
					</div>
					<hr>
				</div>
			</div>
			<input type="submit" value="Update" class="float-right btn btn-primary">
		</form>
		{% url 'courses:detail' course.slug  as detail_url %}
		<a href="{{ next|default:detail_url }}">
			<button class="float-right mr-3 btn btn-outline-primary">Cancel</button>
		</a>
	</div>
{% endblock content %}

{% block custom_style %}
<style type="text/css">
	#div_id_thumbnail div {
	}
</style>
{% endblock custom_style %}

courses/templates/courses/my_courses.html
{% extends "base.html" %}

{% block content %}
	<div class="container text-center bg-light p-5 ol-shadow">
		<h3 class="mb-4 text-primary">
			{% if course_list %}
				Add a course
			{% else %}	
				Sorry, you don't have any courses, yet.
			{% endif %}
		</h3>
		<a class="btn mb-2 px-4 btn-outline-primary btn-lg" href="{% url 'courses:create' %}">
			<i class="mr-1 fas fa-plus-square"></i>
			Add
		</a>

	</div>
	{% if courses %}
		<div class="container mt-5">
			<h3>{{ user_profile.first_name }}'s courses :</h3>
			<div class="row">
			{% for course in courses %}
				{% include "courses/course_item.html" %}
			{% endfor %}
			</div>
		</div>
	{% endif %}

{% endblock content %}